// data.js

const eventsData = [
    { dates: "Lune -145 à -105", title: "La Domination du Torrent", desc: "Étoile de Pluie et Pierre Froide unifient les territoires.", icon: "🔴", type: "war" },
    { dates: "Lune -21", title: "L'Incendie de la Lande", desc: "Un feu ravage le Clan du Vent avant le blizzard.", icon: "🔥", type: "nature" },
    { dates: "Lune -17", title: "Le Grand Blizzard", desc: "La rivière gèle intégralement.", icon: "❄️", type: "nature" },
    { dates: "Lune -7", title: "La Chute de la Rivière", desc: "Le Clan de la Rivière s'effondre totalement.", icon: "🌊", type: "prophecy" },
    { dates: "Lune -5", title: "Le Massacre des Dynastes", desc: "Étoile Douce extermine les solitaires de l'Ombre.", icon: "🩸", type: "war" },
    { dates: "Lune -5", title: "Le Silence Céleste", desc: "Les ancêtres se détournent des vivants.", icon: "✨", type: "prophecy" }
];

const updatesData = [
    { date: "06/05/2026", text: "Inauguration du Panthéon et de la Légende Interactive." },
];

const historicalZones = [
    { id: "torrent", name: "Domination du Torrent", start: -145, end: -105, desc: "Ère d'unification forcée par Étoile de Pluie.", color: "rgba(201, 64, 64, 0.15)" }
];

const creditsData = [
    { role: "Architecture & Code", names: "@.araxia." },
    { role: "Artistes (Dessins)", names: "@Artiste1, @Artiste2, @Artiste3" },
    { role: "Lore & Événements", names: "Staff du serveur Le Prix de la Trêve." },
    { role: "Remerciements Spéciaux", names: "À tous nos joueurs qui font vivre les territoires chaque jour." }
];

const catsData = [
     // --- CLAN DU VENT ---
    { clan: "vent", role: "leaders", name: "Étoile de Châtaigne", start: -300, end: -230, status: "deceased", type: "PNJ", img: "photos/Etoile de Châtaigne - PNJ.png", bio:"Nommé tardivement à l'âge de soixante-dix lunes, il a dirigé le clan avec une bienveillance de grand-père, privilégiant la sagesse et le récit des anciens. Son règne a été marqué par un acte d'héroïsme pur : pour sauver les siens d'une attaque de chiens, il a ordonné une retraite dans les tunnels, se jetant seul dans la bataille pour couvrir la fuite du clan. Bien que le clan soit resté dispersé et meurtri, son sacrifice a permis la survie de la lignée du Vent."},
    { clan: "vent", role: "leaders", name: "Étoile de Boue", start: -230, end: -150, status: "deceased", type: "PNJ", img: "photos/Etoile de Boue - PNJ.png", bio:"Grand stratège au sang-froid exemplaire, il a instauré une ère de prospérité grâce à une alliance inébranlable avec le Clan de l'Ombre. Son règne a été mis à l'épreuve par une invasion insolite de moutons et de bipèdes sur la lande, l'obligeant à adapter son mode de vie pour chasser uniquement de nuit. Sa gestion protectrice et son refus des conflits inutiles en ont fait un chef profondément aimé et respecté."},
    { clan: "vent", role: "leaders", name: "Étoile du Lièvre", start: -150, end: -145, status: "deceased", type: "PNJ", img: "photos/Etoile du Lièvre - PNJ.png", bio:"Fille d'Étoile de Boue, elle a accédé au pouvoir dans le fracas de la tyrannie d'Étoile de Pluie. Meneuse impulsive et courageuse, elle a refusé de plier devant l'oppression. Son destin s'est brisé lors d'un massacre atroce où elle fut attaquée simultanément par deux chefs ennemis. La violence de sa chute fut telle que le combat cessa net, laissant les spectateurs pétrifiés devant la fin de cette meneuse assaillie par le doute."},
    { clan: "vent", role: "leaders", name: "Étoile de Nuit", start: -105, end: -30, status: "deceased", type: "PNJ", img: "photos/Etoile de Nuit - PNJ.png", bio:"Symbole de la reconstruction après la tyrannie, elle a fait revivre les contes de gloire de la lande pour redonner espoir aux siens. Son règne a pris fin de manière mystérieuse : lors d'une patrouille, elle a fait diversion pour sauver son groupe de l'approche de bipèdes. Capturée par ces derniers, elle ne revint jamais, laissant son clan dans l'attente d'une meneuse dont ils n'ont jamais pu faire le deuil."},
    { clan: "vent", role: "leaders", name: "Étoile Blanche", start: -30, end: -22, status: "deceased", type: "PNJ", img: "photos/Etoile Blanche - PNJ.png", bio:"Propulsée au pouvoir par la disparition de sa prédécesseure, elle a régné sous le poids d'un mensonge terrible : n'ayant pu recevoir ses neuf vies car Étoile de Nuit était encore vivante, elle a prétendu être une meneuse légitime pour ne pas laisser le clan sans guide. Dévoilée après sa mort brutale sous les crocs d'un chien, son histoire reste celle d'un sacrifice hanté par la tromperie et un destin inachevé."},
    { clan: "vent", role: "leaders", name: "Étoile de Griffe", start: -22, end: -5, status: "deceased", type: "OC", playedBy: "@/4spic", img: "photos/Etoile de Griffe - PNJ.png", bio:"Meneur choisi directement par les ancêtres après le mensonge d'Étoile Blanche, son règne ne fut qu'une suite de catastrophes : incendie dévastateur, famine et blizzard apocalyptique. Brisé par les épreuves et par une liaison interdite avec la guérisseuse de l'Ombre, il a fini par abandonner ses fonctions pour suivre son cœur. Il est mort banni, laissant derrière lui un clan en ruines et une réputation de traîtrise."},
    { clan: "vent", role: "leaders", name: "Étoile d'Ocre", start: -5, end: 0, status: "active", type: "OC", playedBy: "@pingouin3007", img: "photos/Etoile d'Ocre' - PNJ.png", bio:""},

    { clan: "vent", role: "healers", name: "Griffe Agile", start: -300, end: -210, status: "deceased", type: "PNJ", img: "photos/Griffe Agile - PNJ.png", bio:"Ancien guerrier aguerri aux réflexes vifs, il a surpris tout le monde en étant choisi par le Clan des Étoiles pour devenir guérisseur à quarante lunes. Il a apporté une rigueur militaire à son nouvel art, apprenant les plantes avec une précision chirurgicale. Il est resté le symbole de celui qui peut se réinventer totalement pour servir les siens."},
    { clan: "vent", role: "healers", name: "Cœur de Nacre", start: -210, end: -150, status: "deceased", type: "PNJ", img: "photos/Coeur de Nacre - PNJ.png", bio:"Guérisseur attentif et optimiste, il a exercé durant les années dorées de l'alliance avec l'Ombre. Sa bonté et sa confiance absolue en l'avenir l'ont malheureusement empêché de percevoir la noirceur croissante de son apprentie. Il est mort emporté par la maladie, léguant son savoir à une successeure qui allait corrompre tout son héritage."},
    { clan: "vent", role: "healers", name: "Pierre Froide", start: -150, end: -105, status: "deceased", type: "PNJ", img: "photos/Pierre Froide - PNJ.png", bio:"Antithèse du rôle de guérisseur, elle a utilisé ses gestes doux pour masquer une âme de tueuse. Complice et concubine du tyran Étoile de Pluie, elle a empoisonné ses propres camarades de clan de manière subtile pour éliminer toute résistance au nouveau régime. Elle a disparu sans laisser de traces lors de la chute du Torrent, emportant ses poisons et ses secrets."},
    { clan: "vent", role: "healers", name: "Plume de Blé", start: -105, end: -22, status: "deceased", type: "PNJ", img: "photos/Plume de Blé - PNJ.png", bio:"Héritière d'un savoir corrompu par sa mentore, elle a pourtant exercé avec honnêteté jusqu'à la disparition d'Étoile de Nuit. C'est elle qui a suggéré le mensonge des neuf vies d'Étoile Blanche, croyant sauver la stabilité du clan. Déchue et réduite au rang de guerrière après la révélation de sa tromperie, elle est morte durant le Grand Froid sans avoir trouvé le pardon."},
    { clan: "vent", role: "healers", name: "Éclat du Scarabée", start: -22, end: -1, status: "deceased", type: "OC", playedBy: "@.araxia.", img: "photos/Eclat de Scarabée - PNJ.png", bio:"Guerrière forcée par les ancêtres à devenir guérisseuse alors que la forêt brûlait, elle était cynique et mal aimée, mais indispensable. Elle a porté le clan à bout de bras durant le blizzard et la chute d'Étoile de Griffe, protégeant même les nouveau-nés en secret. Elle est morte en affrontant son ancien meneur, sacrifiant sa vie pour un clan qui ne l'avait jamais vraiment comprise."},
    { clan: "vent", role: "healers", name: "Chant de Cigale", start: -1, end: 0, status: "active", type: "OC", playedBy: "@lavnd.13", img: "photos/default.png", bio:""}, // J'ai ajouté une image par défaut

    // --- CLAN DU TONNERRE ---
    { clan: "tonnerre", role: "leaders", name: "Étoile de Fumée", start: -300, end: -240, status: "deceased", type: "PNJ", img: "photos/Etoile de Fumée - PNJ.png", bio:"Succédant au fondateur, elle a marqué l'histoire par son sacrifice amoureux initial, puis par sa trahison finale envers le Code du Guerrier. Son règne, bien que ferme face à la famine, reste entaché par un secret partagé avec son apprenti guérisseur. Dans un accès de rage qui a pétrifié la forêt, elle a tranché la gorge d'Étoile de Lys, brisant définitivement les rêves d'unification de sa rivale et laissant au Tonnerre une réputation de traîtrise."},
    { clan: "tonnerre", role: "leaders", name: "Étoile d'Orage", start: -240, end: -180, status: "deceased", type: "PNJ", img: "photos/Etoile d'Orage - PNJ.png", bio:"Meneur à l'ambition débordante et au tempérament belliqueux, il a transformé le clan en une machine de guerre. Sa haine viscérale pour Étoile Tachetée l'a poussé à imposer une rigueur militaire à ses troupes pour reconquérir les Rochers du Soleil. Victorieux mais cruel, il a passé son règne à humilier ses adversaires, trouvant une joie sombre dans la détresse de ceux qu'il nommait les Chefs Avides."},
    { clan: "tonnerre", role: "leaders", name: "Étoile de Sable", start: -180, end: -145, status: "deceased", type: "PNJ", img: "photos/Etoile de Sable - PNJ.png", bio:"Chat de paix et de patience, son règne fut paradoxalement l'un des plus violents. Écrasé par une alliance entre l'Ombre et la Rivière, il a vu ses terres envahies et ses guerriers massacrés. Il est mort avec le sentiment d'avoir failli à sa mission divine, la gorge tranchée par le cruel Étoile de Pluie, emportant avec lui l'honneur d'un clan temporairement brisé."},
    { clan: "tonnerre", role: "leaders", name: "Étoile des Bois", start: -105, end: -30, status: "deceased", type: "PNJ", img: "photos/Etoile des Bois - PNJ.png", bio:"Fille d'Étoile de Sable, elle a mené la rébellion contre la tyrannie du Clan du Torrent. Son règne fut celui de la guérison et de la parole libérée. En restaurant l'honneur de son père et en se dévouant corps et âme à son peuple, elle a permis au Tonnerre de briller à nouveau. Elle reste l'image d'une ténacité inébranlable, veillant sur les siens comme un nuage protecteur."},
    { clan: "tonnerre", role: "leaders", name: "Étoile Brumeuse", start: -30, end: -5, status: "deceased", type: "OC", playedBy: "@/c4itvi", img: "photos/Etoile Brumeuse - PNJ.png", bio:"D'abord perçu comme un chef déterminé et protecteur, le poids des saisons et des deuils a fini par glacer son cœur. S'il a su imposer sa domination sur le Clan de l'Ombre, il s'est montré impitoyable envers les rescapés de la Rivière, les traitant comme des prisonniers plutôt que comme des réfugiés. Sa rigidité finale a marqué la fin d'une ère, laissant derrière lui le souvenir d'un meneur au cœur de pierre."},
    { clan: "tonnerre", role: "leaders", name: "Étoile de Framboisier", start: -5, end: 0, status: "active", type: "OC", playedBy: "@.araxia.", img: "photos/default.png", bio:""},

    { clan: "tonnerre", role: "healers", name: "Oiseau de Foudre", start: -300, end: -210, status: "deceased", type: "PNJ", img: "photos/Oiseau de Foudre - PNJ.png", bio:"Guérisseuse à la franchise tranchante, elle n'a jamais hésité à confronter la hiérarchie, allant jusqu'à dénoncer la liaison de sa propre meneuse. Sa vie s'est achevée dans un acte de bravoure pur : elle s'est interposée seule face à une meute de chiens pour permettre à ses blessés de fuir. Elle est l'ancre qui a tenu bon pour que les autres survivent."},
    { clan: "tonnerre", role: "healers", name: "Crinière Obscure", start: -210, end: -110, status: "deceased", type: "PNJ", img: "photos/Crinière Obscure - PNJ.png", bio:"Héritier d'une mentore sacrifiée, il a exercé son art avec une intensité tranquille. Sous la domination sanglante d'Étoile de Pluie, il a incarné la résistance morale en soignant clandestinement les faibles condamnés par le tyran. Exécuté pour sa désobéissance, il est mort les yeux ouverts, refusant de courber l'échine devant la cruauté."},
    { clan: "tonnerre", role: "healers", name: "Braise Cendrée", start: -110, end: -16, status: "deceased", type: "PNJ", img: "photos/Braise Cendrée - PNJ.png", bio:"Véritable survivant, il a traversé les heures les plus sombres du Clan du Torrent en soignant dans l'ombre. Sous le règne d'Étoile des Bois, il est devenu le pilier de la reconstruction, réparant les corps et les esprits avec une patience infinie. Il s'est éteint paisiblement, prouvant que la douceur peut fleurir même sur un sol ravagé par les flammes."},
    { clan: "tonnerre", role: "healers", name: "Aube du Myosotis", start: -16, end: 0, status: "active", type: "OC", playedBy: "@ambre_2704", img: "photos/default.png", bio:""},

    // --- CLAN DE L'OMBRE ---
    { clan: "ombre", role: "leaders", name: "Étoile du Serpent", start: -300, end: -220, status: "deceased", type: "PNJ", img: "photos/Etoile du Serpent - PNJ.png", bio:"Dernière meneuse à avoir côtoyé les fondateurs, elle a régné par la ruse et l'éloquence. Sa complicité avec Étoile de Lys a scellé une alliance historique avec la Rivière, offrant au clan des marais une ère de stabilité et de paix sans précédent."},
    { clan: "ombre", role: "leaders", name: "Étoile de Lierre", start: -220, end: -160, status: "deceased", type: "PNJ", img: "photos/Etoile de Lierre - PNJ.png", bio:"Meneur calme et réfléchi, il a porté la fraternité entre les clans à son apogée. Son amitié avec Étoile de Boue (Clan du Vent) a permis des échanges d'apprentis et un soutien mutuel vital durant les mauvaises saisons, créant un véritable âge d'or diplomatique."},
    { clan: "ombre", role: "leaders", name: "Étoile Sombre", start: -160, end: -145, status: "deceased", type: "PNJ", img: "photos/Etoile Sombre - PNJ.png", bio:"Ambitieux et impitoyable, il a brisé l'âge d'or en assassinant son prédécesseur. Allié à la Pluie Rouge pour soumettre la forêt, il a instauré un régime de terreur et de famine. Son règne s'est achevé dans le sang, égorgé par son propre allié au milieu de ses festins solitaires."},
    { clan: "ombre", role: "leaders", name: "Étoile du Crépuscule", start: -105, end: -30, status: "deceased", type: "PNJ", img: "photos/Etoile du Crépuscule - PNJ.png", bio:"Héros de la rébellion contre le Clan du Torrent, il a restauré les traditions ancestrales d'une patte de fer. Sous son regard d'acier se cachait une générosité immense, faisant de lui un chef protecteur qui n'hésitait jamais à se sacrifier pour le bien-être des siens." },
    { clan: "ombre", role: "leaders", name: "Étoile de Muguet", start: -30, end: -14, status: "deceased", type: "OC", playedBy: "@prince.dante", img: "photos/Etoile de Muguet - PNJ.png", bio:"Meneur albinos à la santé fragile, il a dirigé avec une humilité et une bonté rares. Sa solidarité exemplaire l'a poussé à accueillir le Clan du Vent après l'incendie de la lande. Accablé par le poids de ses responsabilités, il a fini par céder sa place pour redevenir un simple guerrier." },
    { clan: "ombre", role: "leaders", name: "Étoile Douce", start: -14, end: -2, status: "deceased", type: "OC", playedBy: "@fioreale", img: "photos/Etoile Douce - PNJ.png", bio: "Ancienne reine dont la douceur a été brisée par l'invasion des Dynastes. Poussée à bout, elle a orchestré un massacre secret avec l'aide de la Rivière. Rongée par la culpabilité et assaillie par des cauchemars punitifs, elle s'est éteinte affaiblie par une malédiction qui hante encore les marais." },
    { clan: "ombre", role: "leaders", name: "Truffe Champêtre", start: -2, end: 0, status: "active", type: "OC", playedBy: "@l0ops_.", img: "photos/default.png", bio:""},

    { clan: "ombre", role: "healers", name: "Murmure des Eaux", start: -300, end: -240, status: "deceased", type: "PNJ", img: "photos/Murmure des Eaux - PNJ.png", bio:"Bras droit et frère d'Étoile du Serpent, il maniait les remèdes avec la même ruse que sa sœur maniait les mots. Il s'est éteint dans le silence des eaux noires du marais, laissant derrière lui une meneuse brisée par la perte de son conseiller le plus fidèle."},
    { clan: "ombre", role: "healers", name: "Museau d'Orvet", start: -240, end: -140, status: "deceased", type: "PNJ", img: "photos/Museau d'Orvet - PNJ.png", bio:"Guérisseuse méticuleuse confrontée à la cruauté d'Étoile Sombre. Privée de ressources par la gourmandise du meneur, elle est morte en testant sur elle-même un remède incertain, se sacrifiant pour tenter de sauver ses guerriers dans un clan en pleine décomposition."},
    { clan: "ombre", role: "healers", name: "Queue de Serpent", start: -140, end: -20, status: "deceased", type: "PNJ", img: "photos/Queue de Serpent - PNJ.png", bio:"Inspiré par la noblesse des anciens, il a résisté à la tyrannie d'Étoile Sombre et de la Pluie Rouge. Transformant son antre en refuge clandestin, il a protégé les plus vulnérables avant de finir sa vie dans la sérénité d'une paix durement acquise."},
    { clan: "ombre", role: "healers", name: "Brume de Grêle", start: -20, end: -2, status: "retired", type: "OC", playedBy: "@Oriyakii", img: "photos/Brume de Grêle - PNJ.png", bio:"Féline d'une empathie rare, elle a soigné les ennemis d'hier avec le même dévouement que les siens. Déchirée entre son devoir et son amour interdit pour Étoile de Griffe, elle a fini par choisir la liberté, disparaissant du clan une fois son apprentie formée pour suivre son cœur."},
    { clan: "ombre", role: "healers", name: "Illusion du Puceron", start: -2, end: 0, status: "active", type: "OC", playedBy: "@plumeau_", img: "photos/default.png", bio:""},

    // --- CLAN DE LA RIVIÈRE ---
    { clan: "riviere", role: "leaders", name: "Étoile de Lys", start: -300, end: -250, status: "deceased", type: "PNJ", img: "photos/Etoile de Lys - PNJ.png", bio:"Jeune meneuse au « cœur de souris », elle incarnait l'harmonie et la patience. Son rêve était de restaurer l'unité originelle en recréant le « Clan de la Forêt », une ambition qui fut perçue comme une menace par Étoile de Fumée. Elle mourut tragiquement sous les griffes de sa rivale du Tonnerre, s'éteignant avant d'avoir pu voir son idéal de concorde éclore." },
    { clan: "riviere", role: "leaders", name: "Étoile Tachetée", start: -250, end: -175, status: "deceased", type: "PNJ", img: "photos/Etoile Tachetée - PNJ.png", bio:"Successeur robuste et ambitieux, il délaissa les rêves de paix pour se concentrer sur la prospérité territoriale. Son obsession pour les Rochers du Soleil déclencha une guerre sanglante contre Étoile d’Orage. Face à la violence des combats et aux pertes subies par les siens, il préféra une retraite amère à la gloire, laissant derrière lui le souvenir d'un chef dont l'ambition avait coûté trop cher au clan." },
    { clan: "riviere", role: "leaders", name: "Étoile de Pluie", start: -175, end: -145, status: "deceased", type: "PNJ", img: "photos/Etoile de Pluie - PNJ.png", bio:"Tyran manipulateur et sanguinaire, il transforma le clan en une machine de guerre impitoyable. Après avoir assassiné son prédécesseur, il instaura le Clan du Torrent, unifiant les quatre territoires sous un règne de terreur. Connu pour avoir ordonné l'exécution des plus faibles, il tirait son surnom des taches de sang maculant son pelage blanc, rappelant les innombrables meurtres commis pour asseoir son pouvoir absolu." },
    { clan: "riviere", role: "leaders", name: "Étoile de Pluie (Rouge)", start: -145, end: -105, status: "deceased", type: "PNJ", img: "photos/Etoile de Pluie - PNJ.png", bio:"Tyran manipulateur et sanguinaire, il transforma le clan en une machine de guerre impitoyable. Après avoir assassiné son prédécesseur, il instaura le Clan du Torrent, unifiant les quatre territoires sous un règne de terreur. Connu pour avoir ordonné l'exécution des plus faibles, il tirait son surnom des taches de sang maculant son pelage blanc, rappelant les innombrables meurtres commis pour asseoir son pouvoir absolu." },
    { clan: "riviere", role: "leaders", name: "Étoile d'Argent", start: -105, end: -30, status: "deceased", type: "PNJ", img: "photos/Etoile d'Argent - PNJ.png", bio:"Héroïne de la rébellion, elle a abattu la Pluie Rouge pour rendre sa liberté à la forêt. Meneuse d'un courage exemplaire, elle a instauré une période de paix profonde et de reconstruction, évitant soigneusement les tensions diplomatiques pour panser les plaies laissées par le Clan du Torrent. Elle reste l'image de la lumière retrouvée après quarante lunes de ténèbres." },
    { clan: "riviere", role: "leaders", name: "Étoile de Chrysanthème", start: -30, end: -22, status: "deceased", type: "OC", playedBy: "@lavnd.13", img: "photos/Etoile de Chrysanthème - PNJ.png", bio:"Meneur à l'autorité inflexible, il a sombré dans la paranoïa et les rêves de grandeur démesurés. Son règne fut marqué par des bannissements arbitraires et des conflits répétés. Il assassina froidement sa propre guérisseuse, Pelage de Roseau, sur le chemin de la Pierre de Lune avant d'être banni par son propre clan une fois l'atroce vérité découverte." },
    { clan: "riviere", role: "leaders", name: "Aile Sombre", start: -22, end: -7, status: "deceased", type: "OC", playedBy: "@arnisaurus_fr", img: "photos/Aile Sombre - PNJ.png", bio:"Lieutenant porté au pouvoir par un vote démocratique, il a dirigé un clan épuisé par les trahisons. Face au silence du Clan des Étoiles et à la chute symbolique des Quatre Chênes, il prit la décision historique de dissoudre le Clan de la Rivière. Honnête et sans illusions, il a guidé les rescapés vers l'exil, mettant fin à l'existence officielle du clan il y a sept lunes." },

    { clan: "riviere", role: "healers", name: "Coquillage Craquelé", start: -300, end: -220, status: "deceased", type: "PNJ", img: "photos/Coquillage Craquelé - PNJ.png", bio:"Guérisseuse sereine dotée d'une sensibilité rare, elle soignait sans distinction d'appartenance, appliquant les idéaux de paix d'Étoile de Lys. Elle resta le pilier stable du clan durant les ambitions d'Étoile Tachetée, s'éteignant doucement après avoir consacré sa vie à recousser un clan fracturé par la guerre." },
    { clan: "riviere", role: "healers", name: "Roseau Gelé", start: -220, end: -170, status: "deceased", type: "PNJ", img: "photos/Roseau Gelé - PNJ.png", bio:"Disciple de Coquillage Craquelé, il a affronté la tyrannie d'Étoile de Pluie avec une lucidité glaciale. Il fut le seul à s'opposer frontalement au massacre des anciens et des malades ordonné par le tyran. Son refus de baisser le regard devant la cruauté lui coûta la vie, faisant de lui le martyr de l'éthique médicale du clan." },
    { clan: "riviere", role: "healers", name: "Pelage de Roseau", start: -170, end: -27, status: "deceased", type: "PNJ", img: "photos/Pelage de Roseau - PNJ.png", bio:"Devenue guérisseuse dans l'adversité la plus totale, elle a perpétué l'héritage de courage de son mentor. Comprenant la folie d'Étoile de Chrysanthème, elle tenta de l'abattre sans armes, par pure conviction, pour sauver son peuple. Elle fut assassinée par son meneur, mourant les yeux ouverts sur une vérité que le clan finirait par venger." },
    { clan: "riviere", role: "healers", name: "Épis d'Ajonc", start: -27, end: -7, status: "deceased", type: "OC", playedBy: "@/manolo", img: "photos/Epis d'Ajonc - PNJ.png", bio:"Ancien guérisseur devenu guerrier par amour, il reprit ses fonctions après le meurtre de Pelage de Roseau pour assurer la transmission du savoir. Dernier lien avec l'héritage médical de la Rivière, il a accompagné les siens dans l'exil vers le Clan de l'Ombre, s'éteignant paisiblement après une vie de sacrifices et de loyauté." }
];